INTERACTIVE_MODELS_PATH: "./experiments/iter_mask/cocolvis_hrnet18s/000_first-try/checkpoints/"
EXPS_PATH: "./experiments"


# Evaluation datasets
GRABCUT_PATH: "./datasets/GrabCut"
BERKELEY_PATH: "./datasets/Berkeley"
DAVIS_PATH:  "./datasets/DAVIS"
DAVIS17_PATH: "./datasets/davis/"
COCO_MVAL_PATH: "./datasets/COCO_MVal"
PASCALVOC_PATH: "/home/admin/workspace/project/data/datasets/VOC2012/VOCdevkit/VOC2012"
DAVIS585_PATH: "/home/admin/workspace/project/data/datasets/InterDavis/Selected_480P"

# Train datasets
SBD_PATH:  "./datasets/sbd/dataset"
COCO_PATH: "./datasets/coco/"
LVIS_PATH: "./datasets/LVIS/"
LVIS_v1_PATH: "./datasets/coco_lvis"
OPENIMAGES_PATH: "/home/xizhi.cx/data/dataset/OpenImage"
ADE20K_PATH: "/home/admin/workspace/project/data/datasets/ADE20K"

# Extra options for training
THINOBJECT_PATH: "/home/admin/workspace/project/data/datasets/ThinObject/ThinObject5K"
MSRA10K_PATH: "/home/admin/workspace/project/data/datasets/Saliency/MSRA10K_Imgs_GT/Imgs"
DUT_TR_PATH: "/home/admin/workspace/project/data/datasets/Saliency/DUTS-TR/DUTS-TR-Image"
DUT_TE_PATH: "/home/admin/workspace/project/data/datasets/Saliency/DUTS-TE/DUTS-TE-Image"
YTBVOS_PATH: "/home/admin/workspace/project/data/datasets/YTBVOS"
HFLICKER_PATH: "/home/admin/workspace/project/data/datasets/HFlickr"


# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18_SMALL: "./weights/hrnet_w18_small_model_v2.pth"
  HRNETV2_W32: "./weights/hrnet32.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
  SEGFORMER_B0: "/home/admin/workspace/project/data/weights/Segformer/mit_b0.pth"
  SEGFORMER_B1: "/home/admin/workspace/project/data/weights/Segformer/mit_b1.pth"
  SEGFORMER_B3: "/home/admin/workspace/project/data/weights/Segformer/mit_b3.pth"
  PPLCNET_X1 : "/home/admin/workspace/project/data/weights/PPLC/PP-LCNet/PPLCNet_x1_0_ssld_pretrained.pth"
  MOBILENETV2: "/home/admin/workspace/project/data/weights/mobilenetV2-15498621.pth"











